my:
    name: Matheus P Vellone
    email: matheusvellone@hotmail.com
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /blog/:year/:month/:day/:title.html

github:
    url: http://localhost:3000